'use client';
import { useState, useEffect } from 'react';
 
/* ─────────────────────────────── TRANSLATIONS ─────────────────────────────── */
const translations = {
  en: {
    /* Nav */
    home: 'HOME', about: 'ABOUT', services: 'SERVICES', portfolio: 'PORTFOLIO',
    gallery: 'GALLERY', team: 'TEAM', blog: 'BLOG', careers: 'CAREERS',
    pricing: 'PRICING', faq: 'FAQ', contact: 'CONTACT', events: 'EVENTS',
 
    /* Section headings */
    whoWeAre: 'WHO WE ARE',
    aboutTitle: 'About Together Prosperity',
    aboutDesc: "Together Prosperity Private Limited is a next-generation technology company incorporated in India, committed to architecting the nation's digital future through cutting-edge solutions in Blockchain, Cybersecurity, IoT, and Artificial Intelligence.",
    trustedEcosystem: 'TRUSTED ECOSYSTEM',
    sectorsWeServe: 'SECTORS WE SERVE',
    whatWeBuild: 'WHAT WE BUILD',
    coreServices: 'Core Services',
    coreServicesDesc: 'Engineering transformative solutions across six cutting-edge domains.',
    searchServices: 'Search services...',
    learnMore: 'LEARN MORE →',
    caseStudies: 'CASE STUDIES',
    ourWork: 'Our Work',
    ourWorkDesc: 'Real-world impact across sectors',
    clientLove: 'CLIENT LOVE',
    clientsTitle: 'What Our Clients Say',
    clientsDesc: 'Trusted by businesses across India',
    visualGallery: 'VISUAL GALLERY',
    galleryTitle: 'Moments & Milestones',
    galleryDesc: 'A glimpse into our journey and events',
    achievements: 'ACHIEVEMENTS',
    achievementsTitle: 'Our Recognitions',
    achievementsDesc: 'Awards, milestones, and proud moments',
    collaborations: 'COLLABORATIONS',
    collabTitle: 'Our Collaborative Network',
    collabDesc: 'Working together for greater impact',
    insights: 'INSIGHTS',
    blogTitle: 'Latest from Our Blog',
    blogDesc: 'Thought leadership and industry updates',
    searchPosts: 'Search posts...',
    thePeople: 'THE PEOPLE',
    teamTitle: 'Our Team',
    joinUs: 'JOIN US',
    careersTitle: 'Career Opportunities',
    careersDesc: "Be part of India's digital transformation journey",
    pricingTag: 'PRICING',
    pricingTitle: 'Simple, Transparent Pricing',
    pricingDesc: 'Choose the plan that works for you',
    pilotTag: 'PILOT PROGRAM',
    faqTag: 'FAQ',
    faqTitle: 'Frequently Asked Questions',
    faqDesc: 'Everything you need to know about Together Prosperity.',
    getInTouch: 'GET IN TOUCH',
    contactTitle: 'Contact Us',
 
    /* Buttons / CTAs */
    bookDemo: 'BOOK DEMO',
    bookFreeDemo: '📅 BOOK A FREE DEMO',
    exploreServices: 'EXPLORE SERVICES →',
    applyNow: 'Apply Now →',
    getStarted: 'Get Started →',
    applyForPilot: 'APPLY FOR PILOT →',
    sendMessage: '🚀 SEND MESSAGE',
    sending: '⏳ SENDING...',
    sendAnother: '↩ SEND ANOTHER',
    viewAllPhotos: 'VIEW ALL PHOTOS →',
    subscribe: 'Subscribe →',
    submitForApproval: '📤 SUBMIT FOR APPROVAL',
 
    /* Contact section */
    callOrWhatsapp: '📞 CALL OR WHATSAPP',
    emailUs: '✉️ EMAIL US',
    ourLocations: '📍 OUR LOCATIONS',
    kolarOffice: 'Kolar Office',
    bangaloreOffice: 'Bangalore Office',
    followUs: '🌐 FOLLOW US',
    bookADemo: 'BOOK A DEMO',
    letsBuild: "Let's Build Together",
 
    /* Form */
    yourName: 'Your Name *',
    email: 'Email *',
    phone: 'Phone',
    organization: 'Organization',
    selectService: 'Select a service...',
    multipleServices: 'Multiple Services',
    generalInquiry: 'General Inquiry',
    message: 'Message *',
    privacyConsent: 'I agree to the',
    privacyPolicy: 'Privacy Policy',
    privacyConsent2: 'and consent to being contacted.',
    messageSent: 'Message Sent!',
    messageSentDesc: 'Thank you! Our team will contact you within 24 hours.',
 
    /* Newsletter */
    newsletterTitle: '📧 Subscribe to Our Newsletter',
    newsletterDesc: 'Get the latest tech insights, case studies, and exclusive offers.',
    newsletterPlaceholder: 'Enter your email',
    newsletterSuccess: '✅ Thanks for subscribing!',
 
    /* Footer */
    quickLinks: 'QUICK LINKS',
    legal: 'LEGAL',
    privacyPolicyFull: 'Privacy Policy',
    terms: 'Terms of Service',
    cookie: 'Cookie Policy',
    poweredBy: "Powering India's digital transformation through Blockchain, IoT, AI & ML, and Cybersecurity.",
 
    /* Cookie banner */
    cookieText: '🍪 We use cookies to improve your experience.',
    accept: 'ACCEPT',
    decline: 'DECLINE',
 
    /* Misc */
    scroll: 'SCROLL',
    incorporated: 'INCORPORATED 2026',
    karnatakaIndia: 'KARNATAKA · INDIA',
    digitalIndia: 'DIGITAL INDIA ALIGNED',
    estLabel: 'EST. 2026',
    officiallyRegistered: 'OFFICIALLY REGISTERED · COMPANIES ACT 2013 · KARNATAKA, INDIA',
  },
 
  hi: {
    home: 'होम', about: 'हमारे बारे में', services: 'सेवाएं', portfolio: 'पोर्टफोलियो',
    gallery: 'गैलरी', team: 'टीम', blog: 'ब्लॉग', careers: 'करियर',
    pricing: 'मूल्य', faq: 'सवाल', contact: 'संपर्क', events: 'इवेंट',
    whoWeAre: 'हम कौन हैं',
    aboutTitle: 'टुगेदर प्रॉस्पेरिटी के बारे में',
    aboutDesc: 'टुगेदर प्रॉस्पेरिटी प्राइवेट लिमिटेड एक अगली पीढ़ी की प्रौद्योगिकी कंपनी है जो भारत में स्थापित है, और ब्लॉकचेन, साइबर सुरक्षा, IoT और आर्टिफिशियल इंटेलिजेंस में अत्याधुनिक समाधानों के माध्यम से देश के डिजिटल भविष्य को आकार देने के लिए प्रतिबद्ध है।',
    trustedEcosystem: 'विश्वसनीय पारिस्थितिकी तंत्र',
    sectorsWeServe: 'जिन क्षेत्रों में हम काम करते हैं',
    whatWeBuild: 'हम क्या बनाते हैं',
    coreServices: 'मुख्य सेवाएं',
    coreServicesDesc: 'छह अत्याधुनिक क्षेत्रों में परिवर्तनकारी समाधान।',
    searchServices: 'सेवाएं खोजें...',
    learnMore: 'और जानें →',
    caseStudies: 'केस स्टडी',
    ourWork: 'हमारा काम',
    ourWorkDesc: 'विभिन्न क्षेत्रों में वास्तविक प्रभाव',
    clientLove: 'ग्राहक प्रेम',
    clientsTitle: 'हमारे ग्राहक क्या कहते हैं',
    clientsDesc: 'पूरे भारत में व्यवसायों द्वारा विश्वसनीय',
    visualGallery: 'विजुअल गैलरी',
    galleryTitle: 'पल और मील के पत्थर',
    galleryDesc: 'हमारी यात्रा और आयोजनों की एक झलक',
    achievements: 'उपलब्धियां',
    achievementsTitle: 'हमारी पहचान',
    achievementsDesc: 'पुरस्कार, मील के पत्थर और गर्व के पल',
    collaborations: 'सहयोग',
    collabTitle: 'हमारा सहयोगी नेटवर्क',
    collabDesc: 'अधिक प्रभाव के लिए मिलकर काम करना',
    insights: 'अंतर्दृष्टि',
    blogTitle: 'हमारे ब्लॉग से नवीनतम',
    blogDesc: 'विचार नेतृत्व और उद्योग अपडेट',
    searchPosts: 'पोस्ट खोजें...',
    thePeople: 'हमारे लोग',
    teamTitle: 'हमारी टीम',
    joinUs: 'हमसे जुड़ें',
    careersTitle: 'करियर के अवसर',
    careersDesc: 'भारत की डिजिटल परिवर्तन यात्रा का हिस्सा बनें',
    pricingTag: 'मूल्य निर्धारण',
    pricingTitle: 'सरल, पारदर्शी मूल्य निर्धारण',
    pricingDesc: 'आपके लिए सही योजना चुनें',
    pilotTag: 'पायलट प्रोग्राम',
    faqTag: 'सामान्य प्रश्न',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
    faqDesc: 'टुगेदर प्रॉस्पेरिटी के बारे में सब कुछ जो आपको जानना चाहिए।',
    getInTouch: 'संपर्क करें',
    contactTitle: 'हमसे संपर्क करें',
    bookDemo: 'डेमो बुक करें',
    bookFreeDemo: '📅 नि:शुल्क डेमो बुक करें',
    exploreServices: 'सेवाएं देखें →',
    applyNow: 'अभी आवेदन करें →',
    getStarted: 'शुरू करें →',
    applyForPilot: 'पायलट के लिए आवेदन करें →',
    sendMessage: '🚀 संदेश भेजें',
    sending: '⏳ भेज रहे हैं...',
    sendAnother: '↩ दूसरा भेजें',
    viewAllPhotos: 'सभी फ़ोटो देखें →',
    subscribe: 'सदस्यता लें →',
    submitForApproval: '📤 अनुमोदन के लिए जमा करें',
    callOrWhatsapp: '📞 कॉल या व्हाट्सएप',
    emailUs: '✉️ ईमेल करें',
    ourLocations: '📍 हमारे स्थान',
    kolarOffice: 'कोलार कार्यालय',
    bangaloreOffice: 'बैंगलोर कार्यालय',
    followUs: '🌐 हमें फॉलो करें',
    bookADemo: 'डेमो बुक करें',
    letsBuild: 'मिलकर बनाएं',
    yourName: 'आपका नाम *',
    email: 'ईमेल *',
    phone: 'फ़ोन',
    organization: 'संस्था',
    selectService: 'सेवा चुनें...',
    multipleServices: 'एकाधिक सेवाएं',
    generalInquiry: 'सामान्य पूछताछ',
    message: 'संदेश *',
    privacyConsent: 'मैं सहमत हूं',
    privacyPolicy: 'गोपनीयता नीति',
    privacyConsent2: 'और संपर्क किए जाने की सहमति देता/देती हूं।',
    messageSent: 'संदेश भेजा गया!',
    messageSentDesc: 'धन्यवाद! हमारी टीम 24 घंटों के भीतर संपर्क करेगी।',
    newsletterTitle: '📧 हमारे न्यूज़लेटर की सदस्यता लें',
    newsletterDesc: 'नवीनतम तकनीकी अंतर्दृष्टि, केस स्टडी और एक्सक्लूसिव ऑफर पाएं।',
    newsletterPlaceholder: 'अपना ईमेल दर्ज करें',
    newsletterSuccess: '✅ सदस्यता के लिए धन्यवाद!',
    quickLinks: 'त्वरित लिंक',
    legal: 'कानूनी',
    privacyPolicyFull: 'गोपनीयता नीति',
    terms: 'सेवा की शर्तें',
    cookie: 'कुकी नीति',
    poweredBy: 'ब्लॉकचेन, IoT, AI & ML और साइबर सुरक्षा के माध्यम से भारत के डिजिटल परिवर्तन को सशक्त बनाना।',
    cookieText: '🍪 हम आपके अनुभव को बेहतर बनाने के लिए कुकीज़ का उपयोग करते हैं।',
    accept: 'स्वीकार करें',
    decline: 'अस्वीकार करें',
    scroll: 'स्क्रॉल करें',
    incorporated: '2026 में स्थापित',
    karnatakaIndia: 'कर्नाटक · भारत',
    digitalIndia: 'डिजिटल इंडिया संरेखित',
    estLabel: 'स्था. 2026',
    officiallyRegistered: 'आधिकारिक रूप से पंजीकृत · कंपनी अधिनियम 2013 · कर्नाटक, भारत',
  },
 
  kn: {
    home: 'ಮನೆ', about: 'ನಮ್ಮ ಬಗ್ಗೆ', services: 'ಸೇವೆಗಳು', portfolio: 'ಪೋರ್ಟ್‌ಫೋಲಿಯೊ',
    gallery: 'ಗ್ಯಾಲರಿ', team: 'ತಂಡ', blog: 'ಬ್ಲಾಗ್', careers: 'ವೃತ್ತಿ',
    pricing: 'ಬೆಲೆ', faq: 'ಪ್ರಶ್ನೆ', contact: 'ಸಂಪರ್ಕ', events: 'ಕಾರ್ಯಕ್ರಮ',
    whoWeAre: 'ನಾವು ಯಾರು',
    aboutTitle: 'ಟುಗೆದರ್ ಪ್ರಾಸ್ಪೆರಿಟಿ ಬಗ್ಗೆ',
    aboutDesc: 'ಟುಗೆದರ್ ಪ್ರಾಸ್ಪೆರಿಟಿ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್ ಭಾರತದಲ್ಲಿ ಸ್ಥಾಪಿತವಾದ ಮುಂದಿನ ತಲೆಮಾರಿನ ತಂತ್ರಜ್ಞಾನ ಕಂಪನಿಯಾಗಿದ್ದು, ಬ್ಲಾಕ್‌ಚೈನ್, ಸೈಬರ್‌ ಭದ್ರತೆ, IoT ಮತ್ತು ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆಯಲ್ಲಿ ಅತ್ಯಾಧುನಿಕ ಪರಿಹಾರಗಳ ಮೂಲಕ ರಾಷ್ಟ್ರದ ಡಿಜಿಟಲ್ ಭವಿಷ್ಯವನ್ನು ರೂಪಿಸಲು ಬದ್ಧವಾಗಿದೆ.',
    trustedEcosystem: 'ವಿಶ್ವಾಸಾರ್ಹ ಪರಿಸರ ವ್ಯವಸ್ಥೆ',
    sectorsWeServe: 'ನಾವು ಸೇವೆ ಸಲ್ಲಿಸುವ ಕ್ಷೇತ್ರಗಳು',
    whatWeBuild: 'ನಾವು ಏನು ನಿರ್ಮಿಸುತ್ತೇವೆ',
    coreServices: 'ಮೂಲ ಸೇವೆಗಳು',
    coreServicesDesc: 'ಆರು ಅತ್ಯಾಧುನಿಕ ಕ್ಷೇತ್ರಗಳಲ್ಲಿ ಪರಿವರ್ತಕ ಪರಿಹಾರಗಳು.',
    searchServices: 'ಸೇವೆಗಳನ್ನು ಹುಡುಕಿ...',
    learnMore: 'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ →',
    caseStudies: 'ಕೇಸ್ ಸ್ಟಡಿ',
    ourWork: 'ನಮ್ಮ ಕೆಲಸ',
    ourWorkDesc: 'ವಿವಿಧ ಕ್ಷೇತ್ರಗಳಲ್ಲಿ ನೈಜ ಜಗತ್ತಿನ ಪ್ರಭಾವ',
    clientLove: 'ಗ್ರಾಹಕ ಪ್ರೀತಿ',
    clientsTitle: 'ನಮ್ಮ ಗ್ರಾಹಕರು ಏನು ಹೇಳುತ್ತಾರೆ',
    clientsDesc: 'ಭಾರತದಾದ್ಯಂತ ವ್ಯವಹಾರಗಳಿಂದ ವಿಶ್ವಾಸಾರ್ಹ',
    visualGallery: 'ದೃಶ್ಯ ಗ್ಯಾಲರಿ',
    galleryTitle: 'ಕ್ಷಣಗಳು ಮತ್ತು ಮೈಲ್‌ಸ್ಟೋನ್‌ಗಳು',
    galleryDesc: 'ನಮ್ಮ ಪ್ರಯಾಣ ಮತ್ತು ಕಾರ್ಯಕ್ರಮಗಳ ಒಂದು ನೋಟ',
    achievements: 'ಸಾಧನೆಗಳು',
    achievementsTitle: 'ನಮ್ಮ ಮಾನ್ಯತೆಗಳು',
    achievementsDesc: 'ಪ್ರಶಸ್ತಿಗಳು, ಮೈಲ್‌ಸ್ಟೋನ್‌ಗಳು ಮತ್ತು ಹೆಮ್ಮೆಯ ಕ್ಷಣಗಳು',
    collaborations: 'ಸಹಯೋಗಗಳು',
    collabTitle: 'ನಮ್ಮ ಸಹಯೋಗ ನೆಟ್‌ವರ್ಕ್',
    collabDesc: 'ಹೆಚ್ಚಿನ ಪ್ರಭಾವಕ್ಕಾಗಿ ಒಟ್ಟಾಗಿ ಕೆಲಸ ಮಾಡುವುದು',
    insights: 'ಒಳನೋಟಗಳು',
    blogTitle: 'ನಮ್ಮ ಬ್ಲಾಗ್‌ನಿಂದ ಇತ್ತೀಚಿನ ಮಾಹಿತಿ',
    blogDesc: 'ಆಲೋಚನಾ ನಾಯಕತ್ವ ಮತ್ತು ಉದ್ಯಮ ನವೀಕರಣಗಳು',
    searchPosts: 'ಪೋಸ್ಟ್‌ಗಳನ್ನು ಹುಡುಕಿ...',
    thePeople: 'ನಮ್ಮ ಜನರು',
    teamTitle: 'ನಮ್ಮ ತಂಡ',
    joinUs: 'ನಮ್ಮೊಂದಿಗೆ ಸೇರಿ',
    careersTitle: 'ವೃತ್ತಿ ಅವಕಾಶಗಳು',
    careersDesc: 'ಭಾರತದ ಡಿಜಿಟಲ್ ಪರಿವರ್ತನೆ ಯಾತ್ರೆಯ ಭಾಗವಾಗಿ',
    pricingTag: 'ಬೆಲೆ ನಿರ್ಧಾರ',
    pricingTitle: 'ಸರಳ, ಪಾರದರ್ಶಕ ಬೆಲೆ ನಿರ್ಧಾರ',
    pricingDesc: 'ನಿಮಗೆ ಸರಿಹೊಂದುವ ಯೋಜನೆ ಆರಿಸಿ',
    pilotTag: 'ಪೈಲಟ್ ಪ್ರೋಗ್ರಾಂ',
    faqTag: 'ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳು',
    faqTitle: 'ಆಗಾಗ್ಗೆ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು',
    faqDesc: 'ಟುಗೆದರ್ ಪ್ರಾಸ್ಪೆರಿಟಿ ಬಗ್ಗೆ ನೀವು ತಿಳಿಯಬೇಕಾದ ಎಲ್ಲವೂ.',
    getInTouch: 'ಸಂಪರ್ಕಿಸಿ',
    contactTitle: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    bookDemo: 'ಡೆಮೊ ಬುಕ್ ಮಾಡಿ',
    bookFreeDemo: '📅 ಉಚಿತ ಡೆಮೊ ಬುಕ್ ಮಾಡಿ',
    exploreServices: 'ಸೇವೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ →',
    applyNow: 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ →',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ →',
    applyForPilot: 'ಪೈಲಟ್‌ಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ →',
    sendMessage: '🚀 ಸಂದೇಶ ಕಳುಹಿಸಿ',
    sending: '⏳ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...',
    sendAnother: '↩ ಮತ್ತೊಂದು ಕಳುಹಿಸಿ',
    viewAllPhotos: 'ಎಲ್ಲಾ ಫೋಟೋಗಳನ್ನು ನೋಡಿ →',
    subscribe: 'ಚಂದಾದಾರರಾಗಿ →',
    submitForApproval: '📤 ಅನುಮೋದನೆಗೆ ಸಲ್ಲಿಸಿ',
    callOrWhatsapp: '📞 ಕರೆ ಮಾಡಿ ಅಥವಾ ವಾಟ್ಸ್‌ಆ್ಯಪ್ ಮಾಡಿ',
    emailUs: '✉️ ಇಮೇಲ್ ಕಳುಹಿಸಿ',
    ourLocations: '📍 ನಮ್ಮ ಸ್ಥಳಗಳು',
    kolarOffice: 'ಕೋಲಾರ ಕಚೇರಿ',
    bangaloreOffice: 'ಬೆಂಗಳೂರು ಕಚೇರಿ',
    followUs: '🌐 ನಮ್ಮನ್ನು ಅನುಸರಿಸಿ',
    bookADemo: 'ಡೆಮೊ ಬುಕ್ ಮಾಡಿ',
    letsBuild: 'ಒಟ್ಟಾಗಿ ನಿರ್ಮಿಸೋಣ',
    yourName: 'ನಿಮ್ಮ ಹೆಸರು *',
    email: 'ಇಮೇಲ್ *',
    phone: 'ಫೋನ್',
    organization: 'ಸಂಸ್ಥೆ',
    selectService: 'ಸೇವೆ ಆಯ್ಕೆ ಮಾಡಿ...',
    multipleServices: 'ಅನೇಕ ಸೇವೆಗಳು',
    generalInquiry: 'ಸಾಮಾನ್ಯ ವಿಚಾರಣೆ',
    message: 'ಸಂದೇಶ *',
    privacyConsent: 'ನಾನು ಒಪ್ಪುತ್ತೇನೆ',
    privacyPolicy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    privacyConsent2: 'ಮತ್ತು ಸಂಪರ್ಕಿಸಲ್ಪಡಲು ಸಮ್ಮತಿಸುತ್ತೇನೆ.',
    messageSent: 'ಸಂದೇಶ ಕಳುಹಿಸಲಾಗಿದೆ!',
    messageSentDesc: 'ಧನ್ಯವಾದಗಳು! ನಮ್ಮ ತಂಡ 24 ಗಂಟೆಗಳಲ್ಲಿ ಸಂಪರ್ಕಿಸುತ್ತದೆ.',
    newsletterTitle: '📧 ನಮ್ಮ ನ್ಯೂಸ್‌ಲೆಟರ್‌ಗೆ ಚಂದಾದಾರರಾಗಿ',
    newsletterDesc: 'ಇತ್ತೀಚಿನ ತಂತ್ರಜ್ಞಾನ ಒಳನೋಟಗಳು, ಕೇಸ್ ಸ್ಟಡಿಗಳು ಮತ್ತು ವಿಶೇಷ ಕೊಡುಗೆಗಳನ್ನು ಪಡೆಯಿರಿ.',
    newsletterPlaceholder: 'ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ',
    newsletterSuccess: '✅ ಚಂದಾದಾರರಾದಕ್ಕೆ ಧನ್ಯವಾದಗಳು!',
    quickLinks: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    legal: 'ಕಾನೂನು',
    privacyPolicyFull: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    terms: 'ಸೇವಾ ನಿಯಮಗಳು',
    cookie: 'ಕುಕಿ ನೀತಿ',
    poweredBy: 'ಬ್ಲಾಕ್‌ಚೈನ್, IoT, AI & ML ಮತ್ತು ಸೈಬರ್‌ ಭದ್ರತೆಯ ಮೂಲಕ ಭಾರತದ ಡಿಜಿಟಲ್ ಪರಿವರ್ತನೆಯನ್ನು ಸಶಕ್ತಗೊಳಿಸುವುದು.',
    cookieText: '🍪 ನಾವು ನಿಮ್ಮ ಅನುಭವವನ್ನು ಸುಧಾರಿಸಲು ಕುಕೀಗಳನ್ನು ಬಳಸುತ್ತೇವೆ.',
    accept: 'ಒಪ್ಪಿಕೊಳ್ಳಿ',
    decline: 'ನಿರಾಕರಿಸಿ',
    scroll: 'ಸ್ಕ್ರಾಲ್',
    incorporated: '2026ರಲ್ಲಿ ಸ್ಥಾಪಿತ',
    karnatakaIndia: 'ಕರ್ನಾಟಕ · ಭಾರತ',
    digitalIndia: 'ಡಿಜಿಟಲ್ ಇಂಡಿಯಾ ಜೋಡಿಸಲಾಗಿದೆ',
    estLabel: 'ಸ್ಥಾ. 2026',
    officiallyRegistered: 'ಅಧಿಕೃತವಾಗಿ ನೋಂದಾಯಿಸಲಾಗಿದೆ · ಕಂಪನಿ ಕಾಯ್ದೆ 2013 · ಕರ್ನಾಟಕ, ಭಾರತ',
  },
 
  ta: {
    home: 'முகப்பு', about: 'எங்களை பற்றி', services: 'சேவைகள்', portfolio: 'போர்ட்ஃபோலியோ',
    gallery: 'தொகுப்பு', team: 'குழு', blog: 'வலைப்பதிவு', careers: 'வாழ்க்கை',
    pricing: 'விலை', faq: 'கேள்விகள்', contact: 'தொடர்பு', events: 'நிகழ்வுகள்',
    whoWeAre: 'நாங்கள் யார்',
    aboutTitle: 'டுகெதர் ப்ராஸ்பெரிட்டி பற்றி',
    aboutDesc: 'டுகெதர் ப்ராஸ்பெரிட்டி பிரைவேட் லிமிடெட் இந்தியாவில் பதிவு செய்யப்பட்ட அடுத்த தலைமுறை தொழில்நுட்ப நிறுவனம், ப்ளாக்செயின், சைபர் பாதுகாப்பு, IoT மற்றும் செயற்கை நுண்ணறிவு மூலம் நாட்டின் டிஜிட்டல் எதிர்காலத்தை உருவாக்க உறுதிபூண்டுள்ளது.',
    trustedEcosystem: 'நம்பகமான சுற்றுச்சூழல் அமைப்பு',
    sectorsWeServe: 'நாங்கள் சேவை செய்யும் துறைகள்',
    whatWeBuild: 'நாங்கள் என்ன கட்டுகிறோம்',
    coreServices: 'முக்கிய சேவைகள்',
    coreServicesDesc: 'ஆறு அதிநவீன துறைகளில் மாற்றத்தக்க தீர்வுகள்.',
    searchServices: 'சேவைகளைத் தேடுங்கள்...',
    learnMore: 'மேலும் அறிக →',
    caseStudies: 'வழக்கு ஆய்வுகள்',
    ourWork: 'எங்கள் வேலை',
    ourWorkDesc: 'பல்வேறு துறைகளில் நிஜ உலக தாக்கம்',
    clientLove: 'வாடிக்கையாளர் அன்பு',
    clientsTitle: 'எங்கள் வாடிக்கையாளர்கள் என்ன சொல்கிறார்கள்',
    clientsDesc: 'இந்தியா முழுவதும் வணிகங்களால் நம்பகமான',
    visualGallery: 'காட்சி தொகுப்பு',
    galleryTitle: 'தருணங்களும் மைல்கற்களும்',
    galleryDesc: 'எங்கள் பயணம் மற்றும் நிகழ்வுகளின் ஒரு பார்வை',
    achievements: 'சாதனைகள்',
    achievementsTitle: 'எங்கள் அங்கீகாரங்கள்',
    achievementsDesc: 'விருதுகள், மைல்கற்கள் மற்றும் பெருமையான தருணங்கள்',
    collaborations: 'ஒத்துழைப்புகள்',
    collabTitle: 'எங்கள் கூட்டு வலைப்பின்னல்',
    collabDesc: 'அதிக தாக்கத்திற்காக இணைந்து பணியாற்றுதல்',
    insights: 'நுண்ணறிவுகள்',
    blogTitle: 'எங்கள் வலைப்பதிவிலிருந்து சமீபத்தியவை',
    blogDesc: 'சிந்தனை தலைமை மற்றும் தொழில் புதுப்பிப்புகள்',
    searchPosts: 'இடுகைகளைத் தேடுங்கள்...',
    thePeople: 'நம் மக்கள்',
    teamTitle: 'எங்கள் குழு',
    joinUs: 'எங்களுடன் சேருங்கள்',
    careersTitle: 'வாழ்க்கை வாய்ப்புகள்',
    careersDesc: 'இந்தியாவின் டிஜிட்டல் மாற்றப் பயணத்தின் ஒரு பகுதியாகுங்கள்',
    pricingTag: 'விலை நிர்ணயம்',
    pricingTitle: 'எளிய, வெளிப்படையான விலை நிர்ணயம்',
    pricingDesc: 'உங்களுக்கு ஏற்ற திட்டத்தை தேர்வு செய்யுங்கள்',
    pilotTag: 'பைலட் திட்டம்',
    faqTag: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    faqTitle: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    faqDesc: 'டுகெதர் ப்ராஸ்பெரிட்டி பற்றி நீங்கள் தெரிந்துகொள்ள வேண்டியவை அனைத்தும்.',
    getInTouch: 'தொடர்பு கொள்ளுங்கள்',
    contactTitle: 'எங்களை தொடர்பு கொள்ளுங்கள்',
    bookDemo: 'டெமோ பதிவு செய்யுங்கள்',
    bookFreeDemo: '📅 இலவச டெமோ பதிவு செய்யுங்கள்',
    exploreServices: 'சேவைகளை ஆராயுங்கள் →',
    applyNow: 'இப்போதே விண்ணப்பிக்கவும் →',
    getStarted: 'தொடங்குங்கள் →',
    applyForPilot: 'பைலட்டுக்கு விண்ணப்பிக்கவும் →',
    sendMessage: '🚀 செய்தி அனுப்புங்கள்',
    sending: '⏳ அனுப்புகிறோம்...',
    sendAnother: '↩ மற்றொன்று அனுப்புங்கள்',
    viewAllPhotos: 'அனைத்து புகைப்படங்களையும் காணுங்கள் →',
    subscribe: 'சந்தா செலுத்துங்கள் →',
    submitForApproval: '📤 அனுமதிக்கு சமர்ப்பிக்கவும்',
    callOrWhatsapp: '📞 அழையுங்கள் அல்லது வாட்ஸ்அப் செய்யுங்கள்',
    emailUs: '✉️ மின்னஞ்சல் அனுப்புங்கள்',
    ourLocations: '📍 எங்கள் இடங்கள்',
    kolarOffice: 'கோலார் அலுவலகம்',
    bangaloreOffice: 'பெங்களூரு அலுவலகம்',
    followUs: '🌐 எங்களை பின்தொடருங்கள்',
    bookADemo: 'டெமோ பதிவு செய்யுங்கள்',
    letsBuild: 'சேர்ந்து உருவாக்குவோம்',
    yourName: 'உங்கள் பெயர் *',
    email: 'மின்னஞ்சல் *',
    phone: 'தொலைபேசி',
    organization: 'நிறுவனம்',
    selectService: 'சேவையை தேர்வு செய்யுங்கள்...',
    multipleServices: 'பல சேவைகள்',
    generalInquiry: 'பொது விசாரணை',
    message: 'செய்தி *',
    privacyConsent: 'நான் ஒப்புக்கொள்கிறேன்',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    privacyConsent2: 'மற்றும் தொடர்பு கொள்ளப்பட சம்மதிக்கிறேன்.',
    messageSent: 'செய்தி அனுப்பப்பட்டது!',
    messageSentDesc: 'நன்றி! எங்கள் குழு 24 மணி நேரத்திற்குள் தொடர்பு கொள்ளும்.',
    newsletterTitle: '📧 எங்கள் செய்திமடலுக்கு சந்தா செலுத்துங்கள்',
    newsletterDesc: 'சமீபத்திய தொழில்நுட்ப நுண்ணறிவுகள், வழக்கு ஆய்வுகள் மற்றும் சிறப்பு சலுகைகள் பெறுங்கள்.',
    newsletterPlaceholder: 'உங்கள் மின்னஞ்சலை உள்ளிடுங்கள்',
    newsletterSuccess: '✅ சந்தா செலுத்தியதற்கு நன்றி!',
    quickLinks: 'விரைவு இணைப்புகள்',
    legal: 'சட்டம்',
    privacyPolicyFull: 'தனியுரிமைக் கொள்கை',
    terms: 'சேவை விதிமுறைகள்',
    cookie: 'குக்கி கொள்கை',
    poweredBy: 'ப்ளாக்செயின், IoT, AI & ML மற்றும் சைபர் பாதுகாப்பு மூலம் இந்தியாவின் டிஜிட்டல் மாற்றத்தை இயக்குகிறது.',
    cookieText: '🍪 உங்கள் அனுபவத்தை மேம்படுத்த நாங்கள் குக்கிகளைப் பயன்படுத்துகிறோம்.',
    accept: 'ஏற்கவும்',
    decline: 'நிராகரிக்கவும்',
    scroll: 'உருட்டுங்கள்',
    incorporated: '2026இல் நிறுவப்பட்டது',
    karnatakaIndia: 'கர்நாடகா · இந்தியா',
    digitalIndia: 'டிஜிட்டல் இந்தியா இணைந்தது',
    estLabel: 'நிறு. 2026',
    officiallyRegistered: 'அதிகாரப்பூர்வமாக பதிவு செய்யப்பட்டது · நிறுவனங்கள் சட்டம் 2013 · கர்நாடகா, இந்தியா',
  },
 
  te: {
    home: 'హోమ్', about: 'మా గురించి', services: 'సేవలు', portfolio: 'పోర్ట్‌ఫోలియో',
    gallery: 'గ్యాలరీ', team: 'బృందం', blog: 'బ్లాగ్', careers: 'కెరీర్',
    pricing: 'ధర', faq: 'ప్రశ్నలు', contact: 'సంప్రదించు', events: 'ఈవెంట్లు',
    whoWeAre: 'మనం ఎవరు',
    aboutTitle: 'టుగెదర్ ప్రాస్పెరిటీ గురించి',
    aboutDesc: 'టుగెదర్ ప్రాస్పెరిటీ ప్రైవేట్ లిమిటెడ్ భారతదేశంలో నమోదు చేయబడిన తదుపరి తరం సాంకేతిక సంస్థ, బ్లాక్‌చెయిన్, సైబర్ సెక్యూరిటీ, IoT మరియు కృత్రిమ మేధస్సు ద్వారా దేశ డిజిటల్ భవిష్యత్తును నిర్మించడానికి కట్టుబడి ఉంది.',
    trustedEcosystem: 'విశ్వసనీయ పర్యావరణ వ్యవస్థ',
    sectorsWeServe: 'మేము సేవలందించే రంగాలు',
    whatWeBuild: 'మేము ఏమి నిర్మిస్తాము',
    coreServices: 'ముఖ్య సేవలు',
    coreServicesDesc: 'ఆరు అత్యాధునిక రంగాలలో పరివర్తనాత్మక పరిష్కారాలు.',
    searchServices: 'సేవలు వెతకండి...',
    learnMore: 'మరింత తెలుసుకోండి →',
    caseStudies: 'కేస్ స్టడీస్',
    ourWork: 'మా పని',
    ourWorkDesc: 'వివిధ రంగాలలో వాస్తవ ప్రపంచ ప్రభావం',
    clientLove: 'క్లయింట్ ప్రేమ',
    clientsTitle: 'మా క్లయింట్లు ఏమి చెప్తున్నారు',
    clientsDesc: 'భారతదేశంలో వ్యాపారాలచే విశ్వసించబడింది',
    visualGallery: 'దృశ్య గ్యాలరీ',
    galleryTitle: 'క్షణాలు మరియు మైలురాళ్ళు',
    galleryDesc: 'మా ప్రయాణం మరియు ఈవెంట్ల ఒక సంగ్రహం',
    achievements: 'సాధనలు',
    achievementsTitle: 'మా గుర్తింపులు',
    achievementsDesc: 'అవార్డులు, మైలురాళ్ళు మరియు గర్వకారణమైన క్షణాలు',
    collaborations: 'సహకారాలు',
    collabTitle: 'మా సహకార నెట్‌వర్క్',
    collabDesc: 'అధిక ప్రభావం కోసం కలిసి పని చేయడం',
    insights: 'అంతర్దృష్టులు',
    blogTitle: 'మా బ్లాగ్ నుండి తాజా వార్తలు',
    blogDesc: 'ఆలోచనా నాయకత్వం మరియు పరిశ్రమ నవీకరణలు',
    searchPosts: 'పోస్ట్‌లు వెతకండి...',
    thePeople: 'మన ప్రజలు',
    teamTitle: 'మా బృందం',
    joinUs: 'మాతో చేరండి',
    careersTitle: 'కెరీర్ అవకాశాలు',
    careersDesc: 'భారతదేశ డిజిటల్ పరివర్తన ప్రయాణంలో భాగం కండి',
    pricingTag: 'ధర నిర్ణయం',
    pricingTitle: 'సరళ, పారదర్శక ధర నిర్ణయం',
    pricingDesc: 'మీకు అనువైన ప్లాన్ ఎంచుకోండి',
    pilotTag: 'పైలట్ ప్రోగ్రామ్',
    faqTag: 'తరచుగా అడిగే ప్రశ్నలు',
    faqTitle: 'తరచుగా అడిగే ప్రశ్నలు',
    faqDesc: 'టుగెదర్ ప్రాస్పెరిటీ గురించి మీరు తెలుసుకోవలసినది అంతా.',
    getInTouch: 'సంప్రదించండి',
    contactTitle: 'మమ్మల్ని సంప్రదించండి',
    bookDemo: 'డెమో బుక్ చేయండి',
    bookFreeDemo: '📅 ఉచిత డెమో బుక్ చేయండి',
    exploreServices: 'సేవలు అన్వేషించండి →',
    applyNow: 'ఇప్పుడే దరఖాస్తు చేయండి →',
    getStarted: 'ప్రారంభించండి →',
    applyForPilot: 'పైలట్‌కు దరఖాస్తు చేయండి →',
    sendMessage: '🚀 సందేశం పంపండి',
    sending: '⏳ పంపుతున్నాం...',
    sendAnother: '↩ మరొకటి పంపండి',
    viewAllPhotos: 'అన్ని ఫోటోలు చూడండి →',
    subscribe: 'సబ్స్క్రయిబ్ చేయండి →',
    submitForApproval: '📤 అనుమతి కోసం సమర్పించండి',
    callOrWhatsapp: '📞 కాల్ చేయండి లేదా వాట్సాప్ చేయండి',
    emailUs: '✉️ ఇమెయిల్ పంపండి',
    ourLocations: '📍 మా స్థానాలు',
    kolarOffice: 'కోలార్ కార్యాలయం',
    bangaloreOffice: 'బెంగళూరు కార్యాలయం',
    followUs: '🌐 మమ్మల్ని అనుసరించండి',
    bookADemo: 'డెమో బుక్ చేయండి',
    letsBuild: 'కలిసి నిర్మించుదాం',
    yourName: 'మీ పేరు *',
    email: 'ఇమెయిల్ *',
    phone: 'ఫోన్',
    organization: 'సంస్థ',
    selectService: 'సేవ ఎంచుకోండి...',
    multipleServices: 'అనేక సేవలు',
    generalInquiry: 'సాధారణ విచారణ',
    message: 'సందేశం *',
    privacyConsent: 'నేను అంగీకరిస్తున్నాను',
    privacyPolicy: 'గోప్యతా విధానం',
    privacyConsent2: 'మరియు సంప్రదించబడటానికి సమ్మతిస్తున్నాను.',
    messageSent: 'సందేశం పంపబడింది!',
    messageSentDesc: 'ధన్యవాదాలు! మా బృందం 24 గంటల్లో సంప్రదిస్తుంది.',
    newsletterTitle: '📧 మా న్యూస్‌లెటర్‌కు సబ్స్క్రయిబ్ చేయండి',
    newsletterDesc: 'తాజా సాంకేతిక అంతర్దృష్టులు, కేస్ స్టడీస్ మరియు ప్రత్యేక ఆఫర్లు పొందండి.',
    newsletterPlaceholder: 'మీ ఇమెయిల్ నమోదు చేయండి',
    newsletterSuccess: '✅ సబ్స్క్రయిబ్ చేసినందుకు ధన్యవాదాలు!',
    quickLinks: 'త్వరిత లింక్‌లు',
    legal: 'చట్టపరమైన',
    privacyPolicyFull: 'గోప్యతా విధానం',
    terms: 'సేవా నిబంధనలు',
    cookie: 'కుకీ విధానం',
    poweredBy: 'బ్లాక్‌చెయిన్, IoT, AI & ML మరియు సైబర్ సెక్యూరిటీ ద్వారా భారతదేశ డిజిటల్ పరివర్తనకు శక్తి నిస్తోంది.',
    cookieText: '🍪 మీ అనుభవాన్ని మెరుగుపరచడానికి మేము కుకీలను ఉపయోగిస్తాము.',
    accept: 'అంగీకరించండి',
    decline: 'నిరాకరించండి',
    scroll: 'స్క్రోల్',
    incorporated: '2026లో స్థాపించబడింది',
    karnatakaIndia: 'కర్ణాటక · భారతదేశం',
    digitalIndia: 'డిజిటల్ ఇండియా అనుసంధానం',
    estLabel: 'స్థా. 2026',
    officiallyRegistered: 'అధికారికంగా నమోదు చేయబడింది · కంపెనీల చట్టం 2013 · కర్ణాటక, భారతదేశం',
  },
 
  ml: {
    home: 'ഹോം', about: 'ഞങ്ങളെ കുറിച്ച്', services: 'സേവനങ്ങൾ', portfolio: 'പോർട്ട്‌ഫോളിയോ',
    gallery: 'ഗ്യാലറി', team: 'ടീം', blog: 'ബ്ലോഗ്', careers: 'കരിയർ',
    pricing: 'വില', faq: 'ചോദ്യങ്ങൾ', contact: 'ബന്ധപ്പെടുക', events: 'പരിപാടികൾ',
    whoWeAre: 'ഞങ്ങൾ ആരാണ്',
    aboutTitle: 'ടുഗെദർ പ്രോസ്‌പെരിറ്റി കുറിച്ച്',
    aboutDesc: 'ടുഗെദർ പ്രോസ്‌പെരിറ്റി പ്രൈവറ്റ് ലിമിറ്റഡ് ഇന്ത്യയിൽ ഇൻകോർപ്പറേറ്റ് ചെയ്ത അടുത്ത തലമുറ സാങ്കേതിക കമ്പനിയാണ്, ബ്ലോക്‌ചെയിൻ, സൈബർ സുരക്ഷ, IoT, കൃത്രിമ ബുദ്ധി എന്നിവ വഴി രാജ്യത്തിന്റെ ഡിജിറ്റൽ ഭാവി കെട്ടിപ്പടുക്കാൻ പ്രതിജ്ഞാബദ്ധമാണ്.',
    trustedEcosystem: 'വിശ്വസ്ത ആവാസ വ്യവസ്ഥ',
    sectorsWeServe: 'ഞങ്ങൾ സേവനം നൽകുന്ന മേഖലകൾ',
    whatWeBuild: 'ഞങ്ങൾ എന്ത് നിർമ്മിക്കുന്നു',
    coreServices: 'പ്രധാന സേവനങ്ങൾ',
    coreServicesDesc: 'ആറ് അത്യാധുനിക മേഖലകളിൽ പരിവർത്തനകരമായ പരിഹാരങ്ങൾ.',
    searchServices: 'സേവനങ്ങൾ തിരയുക...',
    learnMore: 'കൂടുതൽ അറിയുക →',
    caseStudies: 'കേസ് പഠനങ്ങൾ',
    ourWork: 'ഞങ്ങളുടെ ജോലി',
    ourWorkDesc: 'വിവിധ മേഖലകളിൽ യഥാർത്ഥ ലോക സ്വാധീനം',
    clientLove: 'ക്ലയന്റ് സ്നേഹം',
    clientsTitle: 'ഞങ്ങളുടെ ക്ലയന്റുകൾ എന്ത് പറയുന്നു',
    clientsDesc: 'ഇന്ത്യയിലുടനീളമുള്ള ബിസിനസുകൾ വിശ്വസിക്കുന്നു',
    visualGallery: 'ദൃശ്യ ഗ്യാലറി',
    galleryTitle: 'നിമിഷങ്ങളും നാഴികക്കല്ലുകളും',
    galleryDesc: 'ഞങ്ങളുടെ യാത്രയുടെയും ഇവന്റുകളുടെയും ഒരു നോട്ടം',
    achievements: 'നേട്ടങ്ങൾ',
    achievementsTitle: 'ഞങ്ങളുടെ അംഗീകാരങ്ങൾ',
    achievementsDesc: 'അവാർഡുകൾ, നാഴികക്കല്ലുകൾ, അഭിമാനകരമായ നിമിഷങ്ങൾ',
    collaborations: 'സഹകരണങ്ങൾ',
    collabTitle: 'ഞങ്ങളുടെ സഹകരണ ശൃംഖല',
    collabDesc: 'കൂടുതൽ സ്വാധീനത്തിനായി ഒന്നിച്ച് പ്രവർത്തിക്കുന്നു',
    insights: 'ഉൾക്കാഴ്ചകൾ',
    blogTitle: 'ഞങ്ങളുടെ ബ്ലോഗിൽ നിന്നുള്ള ഏറ്റവും പുതിയത്',
    blogDesc: 'ചിന്താ നേതൃത്വം, വ്യവസായ അപ്ഡേറ്റുകൾ',
    searchPosts: 'പോസ്റ്റുകൾ തിരയുക...',
    thePeople: 'ഞങ്ങളുടെ ആളുകൾ',
    teamTitle: 'ഞങ്ങളുടെ ടീം',
    joinUs: 'ഞങ്ങളോടൊപ്പം ചേരുക',
    careersTitle: 'കരിയർ അവസരങ്ങൾ',
    careersDesc: 'ഇന്ത്യയുടെ ഡിജിറ്റൽ പരിവർത്തന യാത്രയുടെ ഭാഗമാകുക',
    pricingTag: 'വില നിർണ്ണയം',
    pricingTitle: 'ലളിതമായ, സുതാര്യമായ വില നിർണ്ണയം',
    pricingDesc: 'നിങ്ങൾക്ക് അനുയോജ്യമായ പ്ലാൻ തിരഞ്ഞെടുക്കുക',
    pilotTag: 'പൈലറ്റ് പ്രോഗ്രാം',
    faqTag: 'പതിവ് ചോദ്യങ്ങൾ',
    faqTitle: 'പതിവായി ചോദിക്കുന്ന ചോദ്യങ്ങൾ',
    faqDesc: 'ടുഗെദർ പ്രോസ്‌പെരിറ്റിയെ കുറിച്ച് നിങ്ങൾ അറിയേണ്ടതെല്ലാം.',
    getInTouch: 'ബന്ധപ്പെടുക',
    contactTitle: 'ഞങ്ങളെ ബന്ധപ്പെടുക',
    bookDemo: 'ഡെമോ ബുക്ക് ചെയ്യുക',
    bookFreeDemo: '📅 സൗജന്യ ഡെമോ ബുക്ക് ചെയ്യുക',
    exploreServices: 'സേവനങ്ങൾ പര്യവേക്ഷണം ചെയ്യുക →',
    applyNow: 'ഇപ്പോൾ അപേക്ഷിക്കുക →',
    getStarted: 'ആരംഭിക്കുക →',
    applyForPilot: 'പൈലറ്റിന് അപേക്ഷിക്കുക →',
    sendMessage: '🚀 സന്ദേശം അയക്കുക',
    sending: '⏳ അയക്കുന്നു...',
    sendAnother: '↩ മറ്റൊന്ന് അയക്കുക',
    viewAllPhotos: 'എല്ലാ ഫോട്ടോകളും കാണുക →',
    subscribe: 'സബ്സ്ക്രൈബ് ചെയ്യുക →',
    submitForApproval: '📤 അനുമതിക്ക് സമർപ്പിക്കുക',
    callOrWhatsapp: '📞 വിളിക്കുക അല്ലെങ്കിൽ വാട്സ്ആപ്പ് ചെയ്യുക',
    emailUs: '✉️ ഇമെയിൽ അയക്കുക',
    ourLocations: '📍 ഞങ്ങളുടെ സ്ഥാനങ്ങൾ',
    kolarOffice: 'കോലാർ ഓഫീസ്',
    bangaloreOffice: 'ബെംഗളൂരു ഓഫീസ്',
    followUs: '🌐 ഞങ്ങളെ പിന്തുടരുക',
    bookADemo: 'ഡെമോ ബുക്ക് ചെയ്യുക',
    letsBuild: 'ഒന്നിച്ച് നിർമ്മിക്കാം',
    yourName: 'നിങ്ങളുടെ പേര് *',
    email: 'ഇമെയിൽ *',
    phone: 'ഫോൺ',
    organization: 'സ്ഥാപനം',
    selectService: 'സേവനം തിരഞ്ഞെടുക്കുക...',
    multipleServices: 'ഒന്നിലധികം സേവനങ്ങൾ',
    generalInquiry: 'പൊതു അന്വേഷണം',
    message: 'സന്ദേശം *',
    privacyConsent: 'ഞാൻ സമ്മതിക്കുന്നു',
    privacyPolicy: 'സ്വകാര്യതാ നയം',
    privacyConsent2: 'ബന്ധപ്പെടാൻ സമ്മതം നൽകുന്നു.',
    messageSent: 'സന്ദേശം അയച്ചു!',
    messageSentDesc: 'നന്ദി! ഞങ്ങളുടെ ടീം 24 മണിക്കൂറിനുള്ളിൽ ബന്ധപ്പെടും.',
    newsletterTitle: '📧 ഞങ്ങളുടെ ന്യൂസ്‌ലെറ്ററിൽ സബ്സ്ക്രൈബ് ചെയ്യുക',
    newsletterDesc: 'ഏറ്റവും പുതിയ സാങ്കേതിക ഉൾക്കാഴ്ചകൾ, കേസ് പഠനങ്ങൾ, പ്രത്യേക ഓഫറുകൾ നേടുക.',
    newsletterPlaceholder: 'നിങ്ങളുടെ ഇമെയിൽ നൽകുക',
    newsletterSuccess: '✅ സബ്സ്ക്രൈബ് ചെയ്തതിന് നന്ദി!',
    quickLinks: 'ദ്രുത ലിങ്കുകൾ',
    legal: 'നിയമപരം',
    privacyPolicyFull: 'സ്വകാര്യതാ നയം',
    terms: 'സേവന നിബന്ധനകൾ',
    cookie: 'കുക്കി നയം',
    poweredBy: 'ബ്ലോക്‌ചെയിൻ, IoT, AI & ML, സൈബർ സുരക്ഷ വഴി ഇന്ത്യയുടെ ഡിജിറ്റൽ പരിവർത്തനത്തിന് ശക്തി നൽകുന്നു.',
    cookieText: '🍪 നിങ്ങളുടെ അനുഭവം മെച്ചപ്പെടുത്താൻ ഞങ്ങൾ കുക്കികൾ ഉപയോഗിക്കുന്നു.',
    accept: 'സ്വീകരിക്കുക',
    decline: 'നിരസിക്കുക',
    scroll: 'സ്ക്രോൾ',
    incorporated: '2026ൽ സ്ഥാപിതം',
    karnatakaIndia: 'കർണാടക · ഇന്ത്യ',
    digitalIndia: 'ഡിജിറ്റൽ ഇന്ത്യ അനുയോജ്യം',
    estLabel: 'സ്ഥാ. 2026',
    officiallyRegistered: 'ഔദ്യോഗികമായി രജിസ്റ്റർ ചെയ്തു · കമ്പനി ആക്ട് 2013 · കർണാടക, ഇന്ത്യ',
  },
 
  ar: {
    home: 'الرئيسية', about: 'من نحن', services: 'الخدمات', portfolio: 'معرض الأعمال',
    gallery: 'المعرض', team: 'الفريق', blog: 'المدونة', careers: 'الوظائف',
    pricing: 'الأسعار', faq: 'الأسئلة', contact: 'اتصل بنا', events: 'الفعاليات',
    whoWeAre: 'من نحن',
    aboutTitle: 'عن توغيذر بروسبيريتي',
    aboutDesc: 'توغيذر بروسبيريتي برايفيت ليمتد شركة تقنية من الجيل التالي مسجلة في الهند، ملتزمة ببناء مستقبل رقمي للأمة من خلال حلول متطورة في البلوك تشين والأمن السيبراني وإنترنت الأشياء والذكاء الاصطناعي.',
    trustedEcosystem: 'منظومة موثوقة',
    sectorsWeServe: 'القطاعات التي نخدمها',
    whatWeBuild: 'ماذا نبني',
    coreServices: 'الخدمات الأساسية',
    coreServicesDesc: 'حلول تحويلية في ستة مجالات متطورة.',
    searchServices: 'ابحث عن الخدمات...',
    learnMore: 'اعرف المزيد →',
    caseStudies: 'دراسات الحالة',
    ourWork: 'أعمالنا',
    ourWorkDesc: 'تأثير حقيقي عبر القطاعات',
    clientLove: 'محبة العملاء',
    clientsTitle: 'ماذا يقول عملاؤنا',
    clientsDesc: 'موثوق به من قبل الشركات في جميع أنحاء الهند',
    visualGallery: 'معرض مرئي',
    galleryTitle: 'اللحظات والإنجازات',
    galleryDesc: 'لمحة من رحلتنا وفعالياتنا',
    achievements: 'الإنجازات',
    achievementsTitle: 'تقديراتنا',
    achievementsDesc: 'الجوائز والإنجازات واللحظات المفخرة',
    collaborations: 'التعاون',
    collabTitle: 'شبكة تعاوننا',
    collabDesc: 'العمل معاً لتأثير أكبر',
    insights: 'رؤى',
    blogTitle: 'أحدث ما في مدونتنا',
    blogDesc: 'قيادة فكرية وتحديثات الصناعة',
    searchPosts: 'ابحث في المقالات...',
    thePeople: 'فريقنا',
    teamTitle: 'فريقنا',
    joinUs: 'انضم إلينا',
    careersTitle: 'فرص العمل',
    careersDesc: 'كن جزءاً من رحلة التحول الرقمي في الهند',
    pricingTag: 'الأسعار',
    pricingTitle: 'تسعير بسيط وشفاف',
    pricingDesc: 'اختر الخطة المناسبة لك',
    pilotTag: 'برنامج تجريبي',
    faqTag: 'أسئلة شائعة',
    faqTitle: 'الأسئلة المتكررة',
    faqDesc: 'كل ما تحتاج معرفته عن توغيذر بروسبيريتي.',
    getInTouch: 'تواصل معنا',
    contactTitle: 'اتصل بنا',
    bookDemo: 'احجز عرضاً',
    bookFreeDemo: '📅 احجز عرضاً مجانياً',
    exploreServices: 'استكشف الخدمات →',
    applyNow: 'قدّم الآن →',
    getStarted: 'ابدأ الآن →',
    applyForPilot: 'قدّم للبرنامج التجريبي →',
    sendMessage: '🚀 أرسل الرسالة',
    sending: '⏳ جارٍ الإرسال...',
    sendAnother: '↩ أرسل رسالة أخرى',
    viewAllPhotos: 'عرض جميع الصور →',
    subscribe: 'اشترك →',
    submitForApproval: '📤 قدّم للموافقة',
    callOrWhatsapp: '📞 اتصل أو واتساب',
    emailUs: '✉️ راسلنا بالبريد',
    ourLocations: '📍 مواقعنا',
    kolarOffice: 'مكتب كولار',
    bangaloreOffice: 'مكتب بنغالور',
    followUs: '🌐 تابعنا',
    bookADemo: 'احجز عرضاً',
    letsBuild: 'لنبنِ معاً',
    yourName: 'اسمك *',
    email: 'البريد الإلكتروني *',
    phone: 'الهاتف',
    organization: 'المنظمة',
    selectService: 'اختر خدمة...',
    multipleServices: 'خدمات متعددة',
    generalInquiry: 'استفسار عام',
    message: 'الرسالة *',
    privacyConsent: 'أوافق على',
    privacyPolicy: 'سياسة الخصوصية',
    privacyConsent2: 'وأوافق على التواصل معي.',
    messageSent: 'تم إرسال الرسالة!',
    messageSentDesc: 'شكراً! سيتواصل فريقنا معك خلال 24 ساعة.',
    newsletterTitle: '📧 اشترك في نشرتنا البريدية',
    newsletterDesc: 'احصل على أحدث الرؤى التقنية ودراسات الحالة والعروض الحصرية.',
    newsletterPlaceholder: 'أدخل بريدك الإلكتروني',
    newsletterSuccess: '✅ شكراً على اشتراكك!',
    quickLinks: 'روابط سريعة',
    legal: 'قانوني',
    privacyPolicyFull: 'سياسة الخصوصية',
    terms: 'شروط الخدمة',
    cookie: 'سياسة الكوكيز',
    poweredBy: 'تمكين التحول الرقمي للهند عبر البلوك تشين وإنترنت الأشياء والذكاء الاصطناعي والأمن السيبراني.',
    cookieText: '🍪 نستخدم الكوكيز لتحسين تجربتك.',
    accept: 'قبول',
    decline: 'رفض',
    scroll: 'مرر',
    incorporated: 'تأسست 2026',
    karnatakaIndia: 'كارناتاكا · الهند',
    digitalIndia: 'متوافق مع الهند الرقمية',
    estLabel: 'تأس. 2026',
    officiallyRegistered: 'مسجلة رسمياً · قانون الشركات 2013 · كارناتاكا، الهند',
  },
} as const;
 
export type LangCode = keyof typeof translations;
export type Translations = typeof translations[LangCode];
 
const LANG_KEY = 'tp_language';
 
const LANG_META: Record<LangCode, { label: string; native: string; flag: string; rtl?: boolean }> = {
  en: { label: 'EN',      native: 'English',    flag: '🇬🇧' },
  hi: { label: 'हिं',     native: 'हिन्दी',      flag: '🇮🇳' },
  kn: { label: 'ಕನ್ನಡ',   native: 'ಕನ್ನಡ',      flag: '🇮🇳' },
  ta: { label: 'தமிழ்',   native: 'தமிழ்',       flag: '🇮🇳' },
  te: { label: 'తెలుగు',  native: 'తెలుగు',      flag: '🇮🇳' },
  ml: { label: 'മലയ',    native: 'മലയാളം',      flag: '🇮🇳' },
  ar: { label: 'عربي',    native: 'العربية',      flag: '🇸🇦', rtl: true },
};
 
/* ─────────────────────────────── MODULE-LEVEL STORE ──────────────────────── */
let _lang: LangCode = 'en';
const _listeners = new Set<() => void>();
 
function _setLang(lang: LangCode) {
  _lang = lang;
  try {
    localStorage.setItem(LANG_KEY, lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = LANG_META[lang].rtl ? 'rtl' : 'ltr';
  } catch {}
  _listeners.forEach(fn => fn());
}
 
function _loadSaved(): LangCode {
  try {
    const saved = localStorage.getItem(LANG_KEY) as LangCode;
    if (saved && saved in translations) return saved;
  } catch {}
  return 'en';
}
 
/* ─────────────────────────────── HOOK ──────────────────────────────────────── */
export function useLang(): { t: Translations; lang: LangCode; setLang: (l: LangCode) => void } {
  const [, forceUpdate] = useState(0);
 
  useEffect(() => {
    const saved = _loadSaved();
    if (saved !== _lang) {
      _lang = saved;
      document.documentElement.lang = saved;
      document.documentElement.dir = LANG_META[saved].rtl ? 'rtl' : 'ltr';
      forceUpdate(n => n + 1);
    }
    const rerender = () => forceUpdate(n => n + 1);
    _listeners.add(rerender);
    return () => { _listeners.delete(rerender); };
  }, []);
 
  return { t: translations[_lang], lang: _lang, setLang: _setLang };
}
 
/* ─────────────────────────────── SWITCHER COMPONENT ──────────────────────── */
export default function LanguageSwitcher() {
  const { lang } = useLang();
  const [open, setOpen] = useState(false);
 
  const indianLangs = (['hi', 'kn', 'ta', 'te', 'ml'] as LangCode[]);
  const intlLangs   = (['en', 'ar'] as LangCode[]);
 
  return (
    <div style={{ position: 'relative', zIndex: 1100 }}>
      {/* Trigger button */}
      <button
        onClick={() => setOpen(o => !o)}
        style={{
          background: open ? 'rgba(212,160,23,.15)' : 'rgba(255,255,255,.04)',
          border: `1px solid ${open ? 'rgba(212,160,23,.5)' : 'rgba(255,255,255,.1)'}`,
          color: open ? '#D4A017' : 'rgba(255,255,255,.55)',
          padding: '6px 13px',
          borderRadius: '50px',
          fontSize: '9px',
          letterSpacing: '1px',
          fontWeight: 700,
          fontFamily: "'Space Mono', monospace",
          cursor: 'pointer',
          transition: 'all .25s',
          display: 'flex',
          alignItems: 'center',
          gap: '5px',
          whiteSpace: 'nowrap',
        }}
      >
        🌐 {LANG_META[lang].label}
        <span style={{ opacity: 0.5, fontSize: '8px' }}>{open ? '▲' : '▼'}</span>
      </button>
 
      {/* Dropdown */}
      {open && (
        <>
          <div
            style={{ position: 'fixed', inset: 0, zIndex: -1 }}
            onClick={() => setOpen(false)}
          />
          <div
            style={{
              position: 'absolute',
              top: 'calc(100% + 8px)',
              right: 0,
              background: 'rgba(5,5,16,.99)',
              border: '1px solid rgba(212,160,23,.25)',
              borderRadius: '16px',
              overflow: 'hidden',
              boxShadow: '0 20px 60px rgba(0,0,0,.75), 0 0 0 1px rgba(212,160,23,.08)',
              minWidth: '180px',
              maxHeight: '420px',
              overflowY: 'auto',
              animation: 'langDropIn .18s cubic-bezier(.23,1,.32,1)',
            }}
          >
            <style>{`
              @keyframes langDropIn {
                from { opacity:0; transform:translateY(-8px) scale(.96); }
                to   { opacity:1; transform:translateY(0) scale(1); }
              }
            `}</style>
 
            {/* International section */}
            <SectionLabel>INTERNATIONAL</SectionLabel>
            {intlLangs.map(l => (
              <LangOption key={l} l={l} current={lang} onSelect={c => { _setLang(c); setOpen(false); }} />
            ))}
 
            {/* Indian Languages section */}
            <SectionLabel borderTop>INDIAN LANGUAGES</SectionLabel>
            {indianLangs.map(l => (
              <LangOption key={l} l={l} current={lang} onSelect={c => { _setLang(c); setOpen(false); }} />
            ))}
          </div>
        </>
      )}
    </div>
  );
}
 
function SectionLabel({ children, borderTop }: { children: React.ReactNode; borderTop?: boolean }) {
  return (
    <div style={{
      padding: '8px 16px 4px',
      fontSize: '8px',
      letterSpacing: '3px',
      color: 'rgba(212,160,23,.4)',
      fontFamily: "'Space Mono', monospace",
      fontWeight: 700,
      borderTop: borderTop ? '1px solid rgba(255,255,255,.05)' : 'none',
      marginTop: borderTop ? '4px' : 0,
    }}>
      {children}
    </div>
  );
}
 
function LangOption({ l, current, onSelect }: {
  l: LangCode;
  current: LangCode;
  onSelect: (l: LangCode) => void;
}) {
  const meta = LANG_META[l];
  const active = current === l;
 
  return (
    <button
      onClick={() => onSelect(l)}
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        width: '100%',
        padding: '10px 16px',
        background: active ? 'rgba(212,160,23,.12)' : 'transparent',
        border: 'none',
        color: active ? '#D4A017' : 'rgba(255,255,255,.62)',
        fontSize: '12.5px',
        fontWeight: active ? 700 : 400,
        cursor: 'pointer',
        textAlign: 'left',
        transition: 'all .16s',
      }}
      onMouseEnter={e => {
        if (!active) {
          (e.currentTarget as HTMLButtonElement).style.background = 'rgba(212,160,23,.07)';
          (e.currentTarget as HTMLButtonElement).style.color = '#D4A017';
        }
      }}
      onMouseLeave={e => {
        if (!active) {
          (e.currentTarget as HTMLButtonElement).style.background = 'transparent';
          (e.currentTarget as HTMLButtonElement).style.color = 'rgba(255,255,255,.62)';
        }
      }}
    >
      <span style={{ fontSize: '16px', lineHeight: 1, flexShrink: 0 }}>{meta.flag}</span>
      <span style={{ flex: 1 }}>{meta.native}</span>
      {active && <span style={{ fontSize: '11px', color: '#D4A017', flexShrink: 0 }}>✓</span>}
    </button>
  );
}